name: bcode
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  simple_grid: ^0.1.4
  get: 
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  flutter_linkify: ^6.0.0
  flutter_side_menu: ^0.4.0
  collapsible_sidebar: ^2.0.6
  responsive_grid_list: ^1.4.0
  flutter_markdown: ^0.6.18+2
  google_fonts: ^6.1.0
  flutter_neumorphic: 
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor
  flutter_animator: ^3.2.2
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.64.0
  appflowy_editor: ^2.0.0
  textfield_tags: ^2.0.2
  equatable: ^2.0.5
  get_it: ^7.6.4
  flutter_hooks: ^0.20.3
  dio: ^5.3.3
  retrofit: ^4.0.3
  intl: ^0.18.1
  animated_snack_bar: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.4
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/icons/